In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd /content/drive/MyDrive/pro/Data/CSV

/content/drive/MyDrive/pro/Data/CSV


In [ ]:
#module to preprocess the network dataset

import pandas as pd
import numpy as np
from sklearn.utils import shuffle


names = ["frame.time_delta","frame.time_delta_displayed","frame.time_epoch","frame.time_invalid",
"frame.time_relative","eth.src","eth.dst","ip.src","ip.dst","tcp.srcport","tcp.dstport","tcp.flags",
"frame.cap_len","frame.len","frame.number","tcp.stream","tcp.analysis.initial_rtt","tcp.time_delta","tcp.len",
"tcp.window_size_value","tcp.checksum","mqtt.clientid","mqtt.clientid_len","mqtt.conack.flags","mqtt.conack.flags.reserved",
"mqtt.conack.flags.sp","mqtt.conack.val","mqtt.conflag.cleansess","mqtt.conflag.passwd","mqtt.conflag.qos","mqtt.conflag.reserved","mqtt.conflag.retain",
"mqtt.conflag.uname","mqtt.conflag.willflag", "mqtt.conflags","mqtt.dupflag","mqtt.hdrflags","mqtt.kalive","mqtt.len","mqtt.msg","mqtt.msgid","mqtt.msgtype",
"mqtt.passwd","mqtt.passwd_len","mqtt.proto_len","mqtt.protoname","mqtt.qos","mqtt.retain","mqtt.sub.qos","mqtt.suback.qos","mqtt.topic","mqtt.topic_len","mqtt.username",
"mqtt.username_len","mqtt.ver","mqtt.willmsg","mqtt.willmsg_len","mqtt.willtopic","mqtt.willtopic_len","ip.proto"]

In [ ]:
def cleandata(df):
    del df['frame.time_invalid']
    del df['frame.time_epoch']
    del df['frame.time_relative']
    del df['frame.number']
    del df['frame.time_delta']
    del df['frame.time_delta_displayed']
    del df['frame.cap_len']
    del df['frame.len']
    del df['tcp.window_size_value']
    del df['eth.src']
    del df['eth.dst']
    del df['ip.src']
    del df['ip.dst']
    del df['ip.proto']
    del df['tcp.srcport']
    del df['tcp.dstport']
    del df['tcp.analysis.initial_rtt']
    del df['tcp.stream']
    del df['mqtt.topic']
    del df['tcp.checksum']
    del df['mqtt.topic_len'] 
    del df['mqtt.passwd_len']
    del df['mqtt.passwd']
    del df['mqtt.clientid']
    del df['mqtt.clientid_len']
    del df['mqtt.username']
    del df['mqtt.username_len']
    return df

In [ ]:
df_legitimate = pd.read_csv('legitimate_1w.csv',nrows=100000)
df_legitimate.fillna(0, inplace=True)
df_legitimate['target'] = 'normal'
print("Shape of Normal Packet: " + str(df_legitimate.shape))

Shape of Normal Packet: (100000, 61)


/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (21,23,34,45) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [ ]:
df_slowite = pd.read_csv('slowite.csv')
df_slowite.fillna(0, inplace=True)
df_slowite['target'] = 'slowite'
print("Shape of SlowITe: " + str(df_slowite.shape))

Shape of SlowITe: (9202, 61)


In [ ]:
df_malaria = pd.read_csv('malaria.csv')
df_malaria.fillna(0, inplace=True)
df_malaria['target'] = 'dos'
print("Shape of DoS: " + str(df_malaria.shape))

Shape of DoS: (130223, 61)


In [ ]:
df_malformed = pd.read_csv('malformed.csv')
df_malformed.fillna(0, inplace=True)
df_malformed['target'] = 'malformed'
print("Shape of malformed: " + str(df_malformed.shape))

Shape of malformed: (10924, 61)


In [ ]:
df_flood = pd.read_csv('flood.csv')
df_flood.fillna(0, inplace=True)
df_flood['target'] = 'flood'
print("Shape of Flood: " + str(df_flood.shape))

Shape of Flood: (613, 61)


In [ ]:
df_bruteforce = pd.read_csv('bruteforce.csv')
df_bruteforce.fillna(0, inplace=True)
df_bruteforce['target'] = 'bruteforce'
print("Shape of bruteforce:" + str(df_bruteforce.shape))

Shape of bruteforce:(14501, 61)


In [ ]:
print("Starting concatenate dataset")
df = pd.concat([df_legitimate,df_slowite,df_malaria,df_malformed,df_flood,df_bruteforce], ignore_index=True)
df = shuffle(df,random_state=10)
df = cleandata(df)
df.to_csv (r'./mqttdataset.csv', index = False, header=True)

Starting concatenate dataset


In [ ]:
df

tcp.flags  tcp.time_delta  tcp.len mqtt.conack.flags  \
181510  0x00000018        0.000001        8                 0   
121183  0x00000018        0.224572      167                 0   
113802  0x00000018        0.001230        8                 0   
135313  0x00000018        0.000881       16                 0   
56212   0x00000010        0.000003        0                 0   
...            ...             ...      ...               ...   
108445  0x00000010        0.000004        0                 0   
9372    0x00000018        0.000108       14                 0   
105595  0x00000010        0.000905        0                 0   
93553   0x00000018        0.000057       13                 0   
236669  0x00000010        0.000000        0                 0   

        mqtt.conack.flags.reserved  mqtt.conack.flags.sp  mqtt.conack.val  \
181510                         0.0                   0.0              0.0   
121183                         0.0                   0.0              0.0   
113802                         0.0                   0.0              0.0   
135313                         0.0                   0.0              0.0   
56212                          0.0                   0.0              0.0   
...                            ...                   ...              ...   
108445                         0.0                   0.0              0.0   
9372                           0.0                   0.0              0.0   
105595                         0.0                   0.0              0.0   
93553                          0.0                   0.0              0.0   
236669                         0.0                   0.0              0.0   

        mqtt.conflag.cleansess  mqtt.conflag.passwd  mqtt.conflag.qos  ...  \
181510                     0.0                  0.0               0.0  ...   
121183                     0.0                  0.0               0.0  ...   
113802                     0.0                  0.0               0.0  ...   
135313                     0.0                  0.0               0.0  ...   
56212                      0.0                  0.0               0.0  ...   
...                        ...                  ...               ...  ...   
108445                     0.0                  0.0               0.0  ...   
9372                       0.0                  0.0               0.0  ...   
105595                     0.0                  0.0               0.0  ...   
93553                      0.0                  0.0               0.0  ...   
236669                     0.0                  0.0               0.0  ...   

        mqtt.qos  mqtt.retain  mqtt.sub.qos  mqtt.suback.qos mqtt.ver  \
181510       0.0          0.0           0.0              0.0      0.0   
121183       1.0          0.0           0.0              0.0      0.0   
113802       0.0          0.0           0.0              0.0      0.0   
135313       0.0          0.0           0.0              0.0      0.0   
56212        0.0          0.0           0.0              0.0      0.0   
...          ...          ...           ...              ...      ...   
108445       0.0          0.0           0.0              0.0      0.0   
9372         0.0          0.0           0.0              0.0      0.0   
105595       0.0          0.0           0.0              0.0      0.0   
93553        0.0          0.0           0.0              0.0      0.0   
236669       0.0          0.0           0.0              0.0      0.0   

        mqtt.willmsg mqtt.willmsg_len  mqtt.willtopic  mqtt.willtopic_len  \
181510           0.0              0.0             0.0                 0.0   
121183           0.0              0.0             0.0                 0.0   
113802           0.0              0.0             0.0                 0.0   
135313           0.0              0.0             0.0                 0.0   
56212            0.0              0.0             0.0                 0.0   
...              ...       

In [ ]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.layers import Convolution1D, LSTM
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.metrics import plot_confusion_matrix
from warnings import simplefilter
import time
start = time.time()


In [ ]:
df = pd.read_csv("mqttdataset.csv") 
seed = 7
class_names = df.target.unique()
df=df.astype('category')
cat_columns = df.select_dtypes(['category']).columns
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)
y = df['target']
x_columns = df.columns.drop('target')
x = df[x_columns].values


print("Ready to generate train and test datasets")
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=seed)
print("x_train, y_train, x_test, y_test" + str(x_train.shape) + "" +str(y_train.shape) + "" +str(x_test.shape) + "" +str(y_test.shape))

Ready to generate train and test datasets
x_train, y_train, x_test, y_test(185824, 33)(185824,)(79639, 33)(79639,)


In [ ]:
list_of_column_names = list(df.columns)
 
print('List of the features: \n')
for i in list_of_column_names:
  print(i)

List of the features: 

tcp.flags
tcp.time_delta
tcp.len
mqtt.conack.flags
mqtt.conack.flags.reserved
mqtt.conack.flags.sp
mqtt.conack.val
mqtt.conflag.cleansess
mqtt.conflag.passwd
mqtt.conflag.qos
mqtt.conflag.reserved
mqtt.conflag.retain
mqtt.conflag.uname
mqtt.conflag.willflag
mqtt.conflags
mqtt.dupflag
mqtt.hdrflags
mqtt.kalive
mqtt.len
mqtt.msg
mqtt.msgid
mqtt.msgtype
mqtt.proto_len
mqtt.protoname
mqtt.qos
mqtt.retain
mqtt.sub.qos
mqtt.suback.qos
mqtt.ver
mqtt.willmsg
mqtt.willmsg_len
mqtt.willtopic
mqtt.willtopic_len
target


In [ ]:
print(class_names)

['dos' 'normal' 'bruteforce' 'malformed' 'slowite' 'flood']


In [ ]:
len(df)

265463

In [ ]:
print("Ready to generate train and test datasets")

#Neural network
model = Sequential()
model.add(Dense(50, input_dim=x_train.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(30, input_dim=x_train.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(20, kernel_initializer='normal'))
model.add(Dense(6,activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto')
history = model.fit(x_train,y_train,validation_data=(x_test,y_test),callbacks=[monitor],verbose=2,epochs=200,batch_size=1000) 
end = time.time()
diff=end-start
print("Training time: " + str(diff))
starttest = time.time()
y_pred_nn = model.predict(x_test)
y_pred_nn = np.argmax(y_pred_nn,axis=1)
endtest =time.time()
difftest = endtest-starttest
print("Test time: " + str(difftest))

print(model.summary())


Ready to generate train and test datasets
Epoch 1/200
186/186 - 2s - loss: 2.2119 - accuracy: 0.6822 - val_loss: 0.6572 - val_accuracy: 0.7314 - 2s/epoch - 9ms/step
Epoch 2/200
186/186 - 1s - loss: 0.5710 - accuracy: 0.7819 - val_loss: 0.5293 - val_accuracy: 0.7875 - 928ms/epoch - 5ms/step
Epoch 3/200
186/186 - 1s - loss: 0.4833 - accuracy: 0.8155 - val_loss: 0.4565 - val_accuracy: 0.8385 - 896ms/epoch - 5ms/step
Epoch 4/200
186/186 - 1s - loss: 0.4290 - accuracy: 0.8590 - val_loss: 0.4246 - val_accuracy: 0.8641 - 1s/epoch - 6ms/step
Epoch 5/200
186/186 - 1s - loss: 0.3785 - accuracy: 0.8719 - val_loss: 0.3432 - val_accuracy: 0.8764 - 1s/epoch - 6ms/step
Epoch 6/200
186/186 - 1s - loss: 0.3343 - accuracy: 0.8870 - val_loss: 0.3167 - val_accuracy: 0.8932 - 1s/epoch - 6ms/step
Epoch 7/200
186/186 - 1s - loss: 0.3141 - accuracy: 0.8908 - val_loss: 0.3148 - val_accuracy: 0.8940 - 910ms/epoch - 5ms/step
Epoch 8/200
186/186 - 1s - loss: 0.2915 - accuracy: 0.8934 - val_loss: 0.2806 - val_accu

In [ ]:
print("Neural network, accuracy: " + str(metrics.accuracy_score(y_test, y_pred_nn)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred_nn,average='weighted')))
matrixnn = confusion_matrix(y_test,y_pred_nn)
print(matrixnn)

Neural network, accuracy: 0.9106467936563744 F1 score:0.9057172997585536
[[ 3910   485     0     3    23     0]
 [  433 34929     7    32  3496     0]
 [    1     3   101     0    70     0]
 [ 1500   287     3   981   441     1]
 [   31   281     0    12 29732     4]
 [    0     0     0     2     1  2870]]


In [ ]:
x_test

array([[   6,    1,   89, ...,    0,    0,    0],
       [   6,  204,   29, ...,    0,    0,    0],
       [   6, 1106,  182, ...,    0,    0,    0],
       ...,
       [   6,   11,   11, ...,    0,    0,    0],
       [   6,    2,    7, ...,    0,    0,    0],
       [   0,    1,    0, ...,    0,    0,    0]], dtype=int32)

In [ ]:
for i in y_pred_nn:
  print(class_names[i])

Streaming output truncated to the last 5000 lines.
slowite
slowite
normal
normal
dos
normal
normal
normal
normal
flood
normal
normal
slowite
normal
normal
slowite
slowite
slowite
slowite
normal
dos
slowite
normal
slowite
normal
normal
slowite
slowite
normal
slowite
normal
slowite
slowite
normal
normal
dos
slowite
malformed
normal
slowite
normal
normal
dos
dos
slowite
slowite
normal
normal
slowite
flood
normal
slowite
slowite
slowite
slowite
dos
normal
normal
dos
slowite
slowite
normal
dos
dos
normal
normal
slowite
normal
normal
normal
slowite
slowite
dos
dos
slowite
dos
slowite
slowite
slowite
slowite
normal
normal
normal
normal
normal
flood
dos
slowite
normal
dos
normal
normal
normal
normal
normal
normal
normal
flood
normal
normal
slowite
slowite
normal
normal
normal
normal
normal
slowite
normal
normal
dos
slowite
slowite
slowite
slowite
normal
slowite
slowite
slowite
flood
normal
slowite
normal
slowite
slowite
normal
slowite
slowite
normal
slowite
normal
slowite
normal
slowite
normal

In [ ]:
print("Ready to generate new train and test datasets")
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=seed)
print("x_train, y_train, x_test, y_test" + str(x_train.shape) + "" +str(y_train.shape) + "" +str(x_test.shape) + "" +str(y_test.shape))

y_pred_n = model.predict(x_test)
y_pred_n = np.argmax(y_pred_n,axis=1)


Ready to generate new train and test datasets
x_train, y_train, x_test, y_test(159277, 33)(159277,)(106186, 33)(106186,)
3319/3319 [==============================] - 4s 1ms/step


In [ ]:
print("Neural network, accuracy: " + str(metrics.accuracy_score(y_test, y_pred_n)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred_n,average='weighted')))
matrixn = confusion_matrix(y_test,y_pred_n)
print(matrixn)

Neural network, accuracy: 0.9106567720791818 F1 score:0.9056908317176892
[[ 5202   624     0     5    38     0]
 [  561 46576    12    41  4650     0]
 [    1     3   131     0   104     0]
 [ 2015   387     4  1329   595     2]
 [   45   378     0    12 39703     4]
 [    0     0     0     5     1  3758]]


In [ ]:
print("Ready to generate new train and test datasets")
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=seed)
print("x_train, y_train, x_test, y_test" + str(x_train.shape) + "" +str(y_train.shape) + "" +str(x_test.shape) + "" +str(y_test.shape))

y_pred = model.predict(x_test)
y_pred = np.argmax(y_pred,axis=1)

Ready to generate new train and test datasets
x_train, y_train, x_test, y_test(212370, 33)(212370,)(53093, 33)(53093,)
1660/1660 [==============================] - 2s 1ms/step


In [ ]:
print("Neural network, accuracy: " + str(metrics.accuracy_score(y_test, y_pred)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred,average='weighted')))
matrixn = confusion_matrix(y_test,y_pred)
print(matrixn)

Neural network, accuracy: 0.9111182265082026 F1 score:0.9062815683084625
[[ 2589   319     0     2    13     0]
 [  298 23403     5    18  2315     0]
 [    1     2    60     0    47     0]
 [  974   191     2   652   300     1]
 [   21   194     0    10 19738     4]
 [    0     0     0     1     1  1932]]
